language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t liliasimeonova/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true liliasimeonova/docker-react npm run test
